
-
  branches:
    only:
      - master

  image: Visual Studio 2015

  version: 1.0.{build}
  
  init:
    - ps: >-
        if ($env:appveyor_repo_tag -eq "true")
        {
          Update-AppveyorBuild -Version $env:appveyor_repo_tag_name
        }
  
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: {version}
    assembly_file_version: {version}
    assembly_informational_version: {version}

  platform:
    - Any CPU

  configuration:
    - Debug
    - Release

  before_build:
    - cmd: >-
        cd "CreviceApp"
        nuget restore

  build:
    project: CreviceApp.sln
    paralell: false
    verbosity: minimal

  after_test:
    - ps: >-
        $artifact = "crevice"
        mkdir "dist"
        copy "bin" "dist"
        cd "dist"
        del /s "*.xml"
        del /s "*.pdb"
        mkdir "$artifact"
        copy "bin\Release\*" "$artifact"
        7z -a "$artifact.zip" "$artifact"
        Push-AppveyorArtifact "$artifact.zip" -FileName "$artifact.zip" -DeploymentName LatestRelease
        if ($env:appveyor_repo_tag -eq "true")
        {
          Push-AppveyorArtifact "$artifact.zip" -FileName "$artifact.$env:appveyor_repo_tag_name.zip" -DeploymentName TagRelease
        }

#  deploy:
#    - provider: GitHub
#      articact: TagRelease
#      on:
#        branch: master
#        appveyor_repo_tag: true
