
-
  branches:
    only:
      - master

  image: Visual Studio 2015

  version: 1.0.{build}
  
  init:
    - ps: |
        if ($env:appveyor_repo_tag -eq "true")
        {
          Update-AppveyorBuild -Version $env:appveyor_repo_tag_name
        }
  
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  platform:
    - Any CPU

  configuration:
    - Debug
    - Release

  before_build:
    - cmd: |
        cd "CreviceApp"
        nuget restore
        cd ..

  build:
    project: CreviceApp\CreviceApp.sln
    parallel: false
    verbosity: minimal

  after_test:
    - ps: |
        cd "CreviceApp"
        $artifact = "crevice"
        $config = $env:configuration
        if ($config -ne "Release")
        {
          $artifact = "$artifact.$config".ToLower()
        }
        New-Item -Path "dist"
        Copy-Item -Path "bin" -Destination "dist\bin" -Recurse
        cd "dist"
        Get-ChildItem -Include *.xml -Recurse | foreach { $_.Delete() }
        Get-ChildItem -Include *.pdb -Recurse | foreach { $_.Delete() }
        New-Item -Path "$artifact"
        Copy-Item -Path "bin\Release\*" -Destination "$artifact\"
        7z a "$artifact.zip" "$artifact"
        Push-AppveyorArtifact "$artifact.zip" -FileName "$artifact.zip" -DeploymentName "Latest$config"
        if ($env:appveyor_repo_tag -eq "true")
        {
          Push-AppveyorArtifact "$artifact.zip" -FileName "$artifact.$env:appveyor_repo_tag_name.zip" -DeploymentName "Tag$config"
        }
        cd ..

#  deploy:
#    - provider: GitHub
#      articact: TagRelease
#      on:
#        branch: master
#        appveyor_repo_tag: true
