
skip_tags: false
skip_non_tags: false

image: Visual Studio 2017

version: 4.11.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform:
  - Any CPU

environment:
  AppxPackage: false
  GenerateAppxPackageOnBuild: false

configuration:
  - Release

init:
  - git config --global core.autocrlf false

before_build:
  - cmd: |
      nuget restore

build:
  project: Crevice.sln
  parallel: false
  verbosity: minimal

after_test:
  - ps: |
      nuget pack CreviceLib\CreviceLib.csproj.nuspec -Version $env:appveyor_build_version -Symbols
      Get-ChildItem *.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName "nupkg.Latest" }
      if ($tag -eq "true")
      {
        Get-ChildItem *.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName "nupkg.Tag" }
      }
      
      $tag      = $env:appveyor_repo_tag
      $tagname  = $env:appveyor_repo_tag_name
      $artifact = "Crevice.$env:appveyor_build_version.zip"
      
      7z a "$artifact" ".\CreviceApp\bin\Release\*"
      Push-AppveyorArtifact "$artifact" -FileName "$artifact" -DeploymentName "zip.Latest"
      if ($tag -eq "true")
      {
        Push-AppveyorArtifact "$artifact" -FileName "$artifact" -DeploymentName "zip.Tag"
      }

deploy:
  - provider: NuGet
    api_key:
      secure: k0CqiR5hc0+1yWi6u40XhiHYr1Bd1pHPGc5yQj1NuPkDD8vIohYsIZUjLVSa87Ll
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name).$(appveyor_build_number)
    description: Crevice $(appveyor_repo_tag_name).$(appveyor_build_number)
    auth_token:
      secure: rlXYSnSw5pklrVIjalmSFXQO/8RfjbDIpbTlSN2o068LNxFE4WqODJ6uBYjkpFZF
    artifact: zip.Tag
    on:
      appveyor_repo_tag: true
