
skip_tags: false
skip_non_tags: false

image: Visual Studio 2015

version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - cmd: |
      cd "CreviceApp"
      nuget restore
      cd ..

build:
  project: CreviceApp\CreviceApp.sln
  parallel: false
  verbosity: detailed

after_test:
  - ps: |
      cd "CreviceApp"
      $tag     = $env:appveyor_repo_tag
      $tagname = $env:appveyor_repo_tag_name
      $artifact = "crevice"
      Copy-Item -Path "bin" -Destination "dist\bin" -Recurse
      cd "dist"
      Get-ChildItem -Include *.xml -Recurse | foreach { $_.Delete() }
      Get-ChildItem -Include *.pdb -Recurse | foreach { $_.Delete() }
      Copy-Item -Path "bin\Release" -Destination "$artifact" -Recurse
      7z a "$artifact.zip" "$artifact"
      Push-AppveyorArtifact "$artifact.zip" -FileName "$artifact.zip" -DeploymentName "Latest"
      if ($tag -eq "true")
      {
        Push-AppveyorArtifact "$artifact.zip" -FileName "$artifact.$tagname.zip" -DeploymentName "Tag"
      }
      cd ..

#deploy:
#- provider: GitHub
#  auth_token:
#    secure: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#  artifact: Tag
#  on:
#    appveyor_repo_tag: true
