
skip_tags: false
skip_non_tags: false

image: Visual Studio 2017

version: 4.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform:
  - Any CPU

environment:
  AppxPackage: false
  GenerateAppxPackageOnBuild: false

configuration:
  - Release

init:
  - git config --global core.autocrlf false

before_build:
  - cmd: |
      nuget restore

build:
  project: Crevice.sln
  parallel: false
  verbosity: minimal

after_test:
  - ps: |
      nuget pack CreviceLib\CreviceLib.csproj.nuspec -Version $env:appveyor_build_version -Prop Platform=AnyCPU -Prop Configuration=Release
      Get-ChildItem *.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      
      $tag     = $env:appveyor_repo_tag
      $tagname = $env:appveyor_repo_tag_name
      $artifact = Crevice.$env:appveyor_build_version.zip
      
      7z a "$artifact" "CreviceApp\bin\Release\*"
      Push-AppveyorArtifact "$artifact" -FileName "$artifact" -DeploymentName "Latest"
      if ($tag -eq "true")
      {
        Push-AppveyorArtifact "$artifact" -FileName "$artifact" -DeploymentName "Tag"
      }

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name).$(appveyor_build_number)
    description: CreviceApp $(appveyor_repo_tag_name).$(appveyor_build_number)
    auth_token:
      secure: rlXYSnSw5pklrVIjalmSFXQO/8RfjbDIpbTlSN2o068LNxFE4WqODJ6uBYjkpFZF
    artifact: Tag
    on:
      appveyor_repo_tag: true
