
skip_tags: false
skip_non_tags: false

image: Visual Studio 2017

version: 4.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform:
  - Any CPU

environment:
  AppxPackage: false
  GenerateAppxPackageOnBuild: false

configuration:
  - Release

init:
  - git config --global core.autocrlf false

before_build:
  - cmd: |
      nuget restore

build:
  project: Crevice.sln
  parallel: false
  verbosity: minimal

after_test:
  - ps: |
      Get-ChildItem CreviceLib\bin\Release\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      
      cd CreviceApp
      $tag     = $env:appveyor_repo_tag
      $tagname = $env:appveyor_repo_tag_name
      $artifact = "Crevice4"
      Copy-Item -Path "bin" -Destination "dist\bin" -Recurse
      cd "dist"
      Get-ChildItem -Include *.xml -Recurse | foreach { $_.Delete() }
      Get-ChildItem -Include *.pdb -Recurse | foreach { $_.Delete() }
      Copy-Item -Path "bin\Release" -Destination "$artifact" -Recurse
      7z a "$artifact.zip" "$artifact"
      Push-AppveyorArtifact "$artifact.zip" -FileName "$artifact.zip" -DeploymentName "Latest"
      if ($tag -eq "true")
      {
        Push-AppveyorArtifact "$artifact.zip" -FileName "$artifact.$tagname.zip" -DeploymentName "Tag"
      }
      cd ..

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name).$(appveyor_build_number)
    description: CreviceApp $(appveyor_repo_tag_name).$(appveyor_build_number)
    auth_token:
      secure: rlXYSnSw5pklrVIjalmSFXQO/8RfjbDIpbTlSN2o068LNxFE4WqODJ6uBYjkpFZF
    artifact: Tag
    on:
      appveyor_repo_tag: true
